import type { AskContext, Effects, ModuleId, Option, Question } from "./model";

/*
 * The question bank (docs/10 §3). Simple questions, sophisticated scoring:
 * every option nudges a few hidden scores (interest type, academic style,
 * motivations, learning, traits, campus, subjects). Effects are small
 * integers (1–3); a slider's effects scale from −1 (far left) to +1 (far right).
 */

const o = (id: string, label: string, emoji: string, fx: Effects = {}, hint?: string): Option => ({ id, label, emoji, fx, hint });

const abroadOpen = ({ answers }: AskContext) => ["india-abroad", "abroad"].includes(String(answers.distance ?? ""));
const inModule = (m: ModuleId) => (ctx: AskContext) => ctx.modules.includes(m);

export const QUESTIONS: Question[] = [
  /* ------------------------------ 01 YOUR BRAIN ------------------------------ */
  {
    id: "talk",
    chapter: "brain",
    kind: "multi",
    min: 1,
    title: "WHAT COULD YOU TALK ABOUT FOR HOURS?",
    sub: "Pick as many as you like. No judging.",
    options: [
      o("maths", "Maths & puzzles", "🧮", { subjects: { mathematics: 3, statistics: 1, economics: 1, engineering: 1 }, riasec: { I: 2, C: 1 }, academic: { quantitative: 2 } }),
      o("economics", "Economics & money", "📈", { subjects: { economics: 3, finance: 2, commerce: 1 }, riasec: { I: 1, E: 1, C: 1 }, academic: { analytical: 2 } }),
      o("business", "Business & startups", "🚀", { subjects: { business: 3, commerce: 1, finance: 1 }, riasec: { E: 3 }, motivation: { entrepreneurship: 1 } }),
      o("tech", "Computers & tech", "💻", { subjects: { "computer-science": 3, "data-science": 2, engineering: 1 }, riasec: { I: 1, R: 1 }, academic: { technical: 2 } }),
      o("science", "Physics & chemistry", "⚛️", { subjects: { physics: 3, chemistry: 2, engineering: 1 }, riasec: { I: 3 }, academic: { analytical: 1, quantitative: 1 } }),
      o("biology", "Biology & the human body", "🧬", { subjects: { biology: 3, medicine: 2, biotechnology: 1, "allied-health": 1 }, riasec: { I: 2, S: 1 } }),
      o("psychology", "Why people do what they do", "🧠", { subjects: { psychology: 3, sociology: 1 }, riasec: { S: 2, I: 1 }, academic: { social: 2 } }),
      o("history", "History & how the world got here", "🏛️", { subjects: { history: 3, humanities: 1, "political-science": 1 }, riasec: { I: 1, A: 1 }, academic: { verbal: 2 } }),
      o("archaeology", "Ancient worlds & archaeology", "🏺", { subjects: { history: 3, humanities: 1 }, tags: { archaeology: 3, museums: 1 }, riasec: { I: 2, R: 1 } }),
      o("politics", "Politics & current affairs", "🗳️", { subjects: { "political-science": 3, "international-relations": 1, economics: 1 }, tags: { politics: 3 }, riasec: { E: 2, S: 1 }, academic: { verbal: 2 } }),
      o("law", "Law & justice", "⚖️", { subjects: { law: 3, "political-science": 1 }, riasec: { E: 2, S: 1 }, academic: { verbal: 2 } }),
      o("world", "Other countries & world affairs", "🌐", { subjects: { "international-relations": 3, "political-science": 1, geography: 1 }, tags: { ir: 3 }, motivation: { mobility: 1 } }),
      o("literature", "Novels, poetry & literature", "📚", { subjects: { "languages-literature": 3, humanities: 1 }, tags: { literature: 3 }, riasec: { A: 2, I: 1 }, academic: { verbal: 3 } }),
      o("languages", "Learning languages", "🗣️", { subjects: { "languages-literature": 3 }, tags: { languages: 3 }, motivation: { mobility: 1 }, academic: { verbal: 2 } }),
      o("philosophy", "Big questions & philosophy", "🤔", { subjects: { philosophy: 3, humanities: 1 }, riasec: { I: 2, A: 1 }, academic: { analytical: 1, verbal: 2 } }),
      o("design", "Design, art & aesthetics", "🎨", { subjects: { design: 3, "visual-arts": 2, architecture: 1 }, riasec: { A: 3 }, academic: { creative: 3 } }),
      o("film", "Films & cinema", "🎞️", { subjects: { media: 3, "performing-arts": 1 }, tags: { film: 3 }, riasec: { A: 3 }, academic: { creative: 2 } }),
      o("media", "News, content & social media", "📱", { subjects: { media: 3, "languages-literature": 1 }, tags: { journalism: 2 }, riasec: { A: 1, E: 2 }, academic: { creative: 1, verbal: 1 } }),
      o("theatre", "Theatre, music & performance", "🎭", { subjects: { "performing-arts": 3, media: 1 }, tags: { theatre: 3 }, riasec: { A: 3, S: 1 } }),
      o("sport", "Sport & fitness", "⚽", { subjects: { "sports-management": 3, "allied-health": 1 }, riasec: { R: 2, S: 1 }, env: { sport: 2 } }),
      o("planet", "Climate & the planet", "🌱", { subjects: { environmental: 3, geography: 1, agriculture: 1 }, riasec: { I: 1, S: 1, R: 1 }, motivation: { impact: 1 } }),
    ],
  },
  {
    id: "math",
    chapter: "brain",
    kind: "slider",
    title: "HOW MUCH DO YOU LIKE MATH?",
    sub: "Be honest. Nobody's grading this.",
    low: "Please no",
    high: "Love it",
    lowEmoji: "😫",
    highEmoji: "🤩",
    fx: { academic: { quantitative: 3, analytical: 1 }, subjects: { mathematics: 2, statistics: 1, economics: 1, engineering: 1, physics: 1, finance: 1, "data-science": 1 }, riasec: { I: 1, C: 1 } },
  },
  {
    id: "essay",
    chapter: "brain",
    kind: "slider",
    title: "WRITING A LONG, OPINIONATED ESSAY. HOW DOES THAT FEEL?",
    low: "Torture",
    high: "Fun, honestly",
    lowEmoji: "🫠",
    highEmoji: "✍️",
    fx: { academic: { verbal: 3 }, subjects: { "languages-literature": 1, history: 1, law: 1, "political-science": 1, media: 1, philosophy: 1 }, riasec: { A: 1 }, learning: { discussion: 1 } },
  },
  {
    id: "fun",
    chapter: "brain",
    kind: "single",
    title: "WHICH SOUNDS MORE FUN?",
    options: [
      o("exam", "Cracking a tough exam problem", "🧩", { learning: { exam: 3, independent: 1 }, academic: { analytical: 2 }, riasec: { I: 1, C: 1 }, trait: { structure: 1, competition: 1 } }),
      o("project", "Building a real project", "🛠️", { learning: { project: 3, practical: 2 }, academic: { practical: 2, technical: 1 }, riasec: { R: 2 } }),
      o("research", "Researching something nobody has answered", "🔬", { learning: { research: 3, independent: 2 }, riasec: { I: 3 }, motivation: { challenge: 2 } }),
      o("present", "Pitching an idea to a room", "🎤", { learning: { discussion: 3, collaborative: 1 }, riasec: { E: 3 }, academic: { verbal: 1, social: 1 } }),
    ],
  },
  {
    id: "why",
    chapter: "brain",
    kind: "slider",
    title: "HOW MUCH DO YOU ENJOY FIGURING OUT WHY THINGS WORK?",
    low: "Just tell me",
    high: "Must know",
    lowEmoji: "🤷",
    highEmoji: "🔍",
    fx: { riasec: { I: 3 }, academic: { analytical: 2 }, motivation: { challenge: 1 }, learning: { research: 1 } },
  },
  {
    id: "friends",
    chapter: "brain",
    kind: "single",
    title: "YOUR FRIENDS USUALLY COME TO YOU FOR…",
    options: [
      o("homework", "Help with homework", "📐", { academic: { analytical: 2, quantitative: 1 }, riasec: { I: 2 } }),
      o("advice", "Life advice", "💬", { academic: { social: 2 }, riasec: { S: 3 } }),
      o("plans", "Making the plan happen", "🗓️", { riasec: { C: 2, E: 1 }, trait: { structure: 2 } }),
      o("creative", "Anything creative", "✨", { riasec: { A: 3 }, academic: { creative: 2 } }),
      o("fix", "Fixing their phone or laptop", "🔧", { riasec: { R: 2, I: 1 }, academic: { technical: 2 } }),
      o("deals", "Getting a good deal", "🤑", { riasec: { E: 2, C: 1 }, motivation: { income: 1 } }),
    ],
  },

  /* ------------------------------ 02 YOUR ENERGY ----------------------------- */
  {
    id: "saturday",
    chapter: "energy",
    kind: "multi",
    min: 1,
    title: "YOU HAVE A FREE SATURDAY. WHAT ARE YOU DOING?",
    sub: "Pick everything that sounds like you.",
    options: [
      o("business", "Working on a side hustle", "💼", { riasec: { E: 3 }, motivation: { entrepreneurship: 2 }, subjects: { business: 1 } }),
      o("code", "Coding something", "⌨️", { riasec: { I: 1, R: 1 }, academic: { technical: 2 }, subjects: { "computer-science": 2 } }),
      o("sport", "Playing sport", "🏏", { riasec: { R: 2 }, env: { sport: 2 }, subjects: { "sports-management": 1 } }),
      o("invest", "Reading about markets & investing", "📊", { riasec: { E: 1, C: 2 }, subjects: { finance: 2, economics: 1 }, motivation: { income: 1 } }),
      o("design", "Drawing or designing", "🖌️", { riasec: { A: 3 }, subjects: { design: 2, "visual-arts": 1 } }),
      o("travel", "Exploring a new place", "🧭", { motivation: { mobility: 2 }, trait: { flexibility: 1, risk: 1 }, env: { international: 1 } }),
      o("read", "Reading", "📖", { riasec: { I: 1, A: 1 }, academic: { verbal: 2 } }),
      o("content", "Making videos or content", "📱", { riasec: { A: 2, E: 1 }, subjects: { media: 2 } }),
      o("friends", "Hanging out with friends", "🎉", { riasec: { S: 2 }, env: { campusLife: 2, culture: 1 } }),
      o("volunteer", "Volunteering", "🫶", { riasec: { S: 3 }, motivation: { impact: 2 }, subjects: { "social-work": 1 } }),
      o("films", "Watching — and dissecting — films", "🍿", { riasec: { A: 2, I: 1 }, subjects: { media: 2 }, tags: { film: 2 } }),
      o("write", "Writing stories or poetry", "🖋️", { riasec: { A: 3 }, subjects: { "languages-literature": 2 }, tags: { "creative-writing": 3, literature: 1 } }),
      o("museum", "Exploring a museum or heritage site", "🏛️", { riasec: { I: 1, A: 1 }, subjects: { history: 2 }, tags: { museums: 2, archaeology: 1 } }),
      o("debate", "Debating or Model UN", "🎙️", { riasec: { E: 2, S: 1 }, subjects: { "political-science": 1, "international-relations": 1, law: 1 }, tags: { politics: 1, ir: 1 }, learning: { discussion: 1 } }),
    ],
  },
  {
    id: "startup",
    chapter: "energy",
    kind: "slider",
    title: "HOW MUCH WOULD YOU ENJOY STARTING A BUSINESS?",
    low: "Stress, no thanks",
    high: "Dream",
    lowEmoji: "😬",
    highEmoji: "🚀",
    fx: { riasec: { E: 3 }, motivation: { entrepreneurship: 3 }, trait: { risk: 2 }, env: { entrepreneurial: 2 }, subjects: { business: 1 } },
  },
  {
    id: "apart",
    chapter: "energy",
    kind: "slider",
    title: "TAKING SOMETHING APART TO SEE HOW IT WORKS?",
    low: "Not my thing",
    high: "Already did it",
    lowEmoji: "🙅",
    highEmoji: "🪛",
    fx: { riasec: { R: 3, I: 1 }, academic: { technical: 2, practical: 1 }, subjects: { engineering: 2, physics: 1 } },
  },
  {
    id: "teach",
    chapter: "energy",
    kind: "slider",
    title: "EXPLAINING SOMETHING UNTIL A FRIEND FINALLY GETS IT?",
    low: "Draining",
    high: "So satisfying",
    lowEmoji: "😮‍💨",
    highEmoji: "💡",
    fx: { riasec: { S: 3 }, academic: { social: 2, verbal: 1 }, motivation: { impact: 1 }, subjects: { education: 1, psychology: 1 } },
  },
  {
    id: "beautiful",
    chapter: "energy",
    kind: "slider",
    title: "MAKING SOMETHING THAT LOOKS BEAUTIFUL?",
    low: "Meh",
    high: "Obsessed",
    lowEmoji: "😐",
    highEmoji: "😍",
    fx: { riasec: { A: 3 }, academic: { creative: 3 }, motivation: { creativity: 2 }, subjects: { design: 2, architecture: 1, "visual-arts": 1 } },
  },
  {
    id: "organise",
    chapter: "energy",
    kind: "slider",
    title: "TURNING TOTAL CHAOS INTO A PERFECT SYSTEM?",
    sub: "Think: a flawless spreadsheet, a colour-coded plan.",
    low: "Chaos is fine",
    high: "Deeply satisfying",
    lowEmoji: "🌪️",
    highEmoji: "🗂️",
    fx: { riasec: { C: 3 }, trait: { structure: 2 }, subjects: { commerce: 1, statistics: 1, finance: 1 } },
  },
  {
    id: "projects",
    chapter: "energy",
    kind: "rank",
    pick: 3,
    title: "RANK YOUR TOP 3 PROJECTS.",
    sub: "Tap in order — first tap is your favourite.",
    options: [
      o("app", "Build an app people use", "📲", { riasec: { R: 1, I: 1 }, subjects: { "computer-science": 3, "data-science": 1 } }),
      o("fundraiser", "Run a fundraiser", "🎗️", { riasec: { E: 2, S: 2 }, motivation: { impact: 1 }, subjects: { business: 1, "social-work": 1 } }),
      o("disease", "Research a disease", "🦠", { riasec: { I: 3 }, subjects: { biology: 2, medicine: 2, biotechnology: 1 } }),
      o("brand", "Design a brand", "🎨", { riasec: { A: 3 }, subjects: { design: 3, media: 1, business: 1 } }),
      o("policy", "Debate a new law", "🗳️", { riasec: { E: 2, S: 1 }, subjects: { law: 2, "political-science": 2 } }),
      o("stocks", "Predict the stock market with data", "📈", { riasec: { I: 2, C: 2 }, subjects: { finance: 3, "data-science": 1, economics: 1 } }),
      o("bridge", "Design a bridge or a machine", "🏗️", { riasec: { R: 3 }, subjects: { engineering: 3, architecture: 1 } }),
      o("story", "Write a story or make a film", "🎞️", { riasec: { A: 3 }, subjects: { media: 2, "languages-literature": 2 } }),
    ],
  },

  /* -------------------- deep dives (two chosen adaptively) -------------------- */
  {
    id: "dd-money-crash",
    chapter: "energy",
    module: "money",
    when: inModule("money"),
    kind: "single",
    title: "THE MARKET JUST DROPPED 20%. YOUR FIRST THOUGHT?",
    options: [
      o("buy", "Time to buy", "🛒", { trait: { risk: 3 }, subjects: { finance: 2 }, riasec: { E: 1 } }),
      o("why", "Why did it happen?", "🧐", { riasec: { I: 2 }, subjects: { economics: 3 } }),
      o("model", "Let me model the risk", "🧮", { riasec: { C: 1, I: 1 }, subjects: { statistics: 2, finance: 2, mathematics: 1 } }),
      o("panic", "Honestly? Panic", "😅", { trait: { risk: -2 }, motivation: { security: 2 } }),
    ],
  },
  {
    id: "dd-money-role",
    chapter: "energy",
    module: "money",
    when: inModule("money"),
    kind: "single",
    title: "PICK THE MONEY JOB THAT SOUNDS MOST LIKE YOU.",
    options: [
      o("quant", "Build pricing models", "📐", { subjects: { finance: 2, mathematics: 2, "data-science": 1 }, academic: { quantitative: 2 } }),
      o("pitch", "Pitch a deal to investors", "🤝", { subjects: { finance: 2, business: 2 }, riasec: { E: 2 }, motivation: { income: 1 } }),
      o("econ", "Explain why some countries get rich", "🌍", { subjects: { economics: 3, "political-science": 1 }, riasec: { I: 2 } }),
      o("ops", "Run a company's operations", "⚙️", { subjects: { business: 3, commerce: 1 }, riasec: { C: 2, E: 1 } }),
    ],
  },
  {
    id: "dd-money-data",
    chapter: "energy",
    module: "money",
    when: inModule("money"),
    kind: "slider",
    title: "HOW MUCH DO YOU ENJOY WORKING WITH DATA & STATISTICS?",
    low: "Not much",
    high: "A lot",
    lowEmoji: "📉",
    highEmoji: "📊",
    fx: { subjects: { statistics: 2, "data-science": 2, economics: 1, finance: 1 }, academic: { quantitative: 2 } },
  },
  {
    id: "dd-tech-build",
    chapter: "energy",
    module: "tech",
    when: inModule("tech"),
    kind: "single",
    title: "WHAT WOULD YOU RATHER BUILD?",
    options: [
      o("app", "An app millions use", "📱", { subjects: { "computer-science": 3 } }),
      o("ai", "An AI that learns", "🤖", { subjects: { "data-science": 3, "computer-science": 1, mathematics: 1 } }),
      o("robot", "A robot or a drone", "🦾", { subjects: { engineering: 3 }, riasec: { R: 2 } }),
      o("city", "Bridges, buildings, cities", "🌉", { subjects: { engineering: 2, architecture: 2 }, riasec: { R: 2 } }),
      o("security", "Systems hackers can't break", "🔐", { subjects: { "computer-science": 3 }, riasec: { C: 1 } }),
    ],
  },
  {
    id: "dd-tech-hw",
    chapter: "energy",
    module: "tech",
    when: inModule("tech"),
    kind: "versus",
    title: "HARDWARE OR SOFTWARE?",
    options: [
      o("hardware", "Things you can touch", "🔩", { subjects: { engineering: 3, physics: 1 }, riasec: { R: 2 } }),
      o("software", "Things that run on a screen", "🖥️", { subjects: { "computer-science": 3 }, riasec: { I: 1 } }),
    ],
  },
  {
    id: "dd-tech-code",
    chapter: "energy",
    module: "tech",
    when: inModule("tech"),
    kind: "slider",
    title: "WOULD YOU CODE FOR FUN ON A WEEKEND?",
    low: "Never",
    high: "Already do",
    lowEmoji: "🙃",
    highEmoji: "👩‍💻",
    fx: { subjects: { "computer-science": 3, "data-science": 1 }, academic: { technical: 2 } },
  },
  {
    id: "dd-health-where",
    chapter: "energy",
    module: "health",
    when: inModule("health"),
    kind: "single",
    title: "WHERE DO YOU SEE YOURSELF?",
    options: [
      o("hospital", "In a hospital, treating patients", "🩺", { subjects: { medicine: 3, nursing: 1, "allied-health": 1 }, riasec: { S: 2, I: 1 } }),
      o("lab", "In a lab, finding cures", "🧪", { subjects: { biotechnology: 2, biology: 2, chemistry: 1 }, riasec: { I: 3 } }),
      o("counsel", "In a counselling room", "🛋️", { subjects: { psychology: 3 }, riasec: { S: 3 } }),
      o("pharma", "Making medicines", "💊", { subjects: { pharmacy: 3, chemistry: 1 }, riasec: { I: 1, C: 1 } }),
    ],
  },
  {
    id: "dd-health-long",
    chapter: "energy",
    module: "health",
    when: inModule("health"),
    kind: "slider",
    title: "OKAY WITH 5+ YEARS OF TRAINING BEFORE YOU'RE FULLY QUALIFIED?",
    low: "Too long",
    high: "Worth it",
    lowEmoji: "⏳",
    highEmoji: "🎓",
    fx: { subjects: { medicine: 3 }, trait: { ambition: 1 }, motivation: { security: 1 } },
  },
  {
    id: "dd-health-scale",
    chapter: "energy",
    module: "health",
    when: inModule("health"),
    kind: "versus",
    title: "WHICH MATTERS MORE TO YOU?",
    options: [
      o("one", "Helping the person in front of me", "🫂", { subjects: { medicine: 2, nursing: 1, psychology: 1 }, riasec: { S: 2 } }),
      o("millions", "Improving health for millions", "🌐", { subjects: { biotechnology: 1, "data-science": 1, "social-sciences": 1 }, riasec: { I: 2 }, motivation: { impact: 2 } }),
    ],
  },
  {
    id: "dd-design-make",
    chapter: "energy",
    module: "design",
    when: inModule("design"),
    kind: "single",
    title: "WHAT WOULD YOU LOVE TO MAKE?",
    options: [
      o("building", "A building people remember", "🏛️", { subjects: { architecture: 3 }, riasec: { R: 1, A: 2 } }),
      o("ux", "An app that feels effortless", "📲", { subjects: { design: 3, "computer-science": 1 }, riasec: { A: 2, I: 1 } }),
      o("film", "A film or a campaign", "🎬", { subjects: { media: 3 }, riasec: { A: 2, E: 1 } }),
      o("fashion", "A fashion line", "👗", { subjects: { design: 3 }, riasec: { A: 3 } }),
      o("art", "Art for a gallery", "🖼️", { subjects: { "visual-arts": 3 }, riasec: { A: 3 } }),
    ],
  },
  {
    id: "dd-design-why",
    chapter: "energy",
    module: "design",
    when: inModule("design"),
    kind: "versus",
    title: "DESIGN SHOULD…",
    options: [
      o("express", "Express something", "🎭", { subjects: { "visual-arts": 2, "performing-arts": 1 }, riasec: { A: 3 } }),
      o("solve", "Solve a problem", "🧩", { subjects: { design: 2, engineering: 1, architecture: 1 }, riasec: { I: 1, R: 1 } }),
    ],
  },
  {
    id: "dd-design-sketch",
    chapter: "energy",
    module: "design",
    when: inModule("design"),
    kind: "slider",
    title: "DO YOU THINK IN PICTURES — SKETCHING IDEAS BEFORE WORDS?",
    low: "Words first",
    high: "Always sketching",
    lowEmoji: "📝",
    highEmoji: "✏️",
    fx: { academic: { creative: 2 }, subjects: { design: 2, architecture: 1, "visual-arts": 1 } },
  },
  {
    id: "dd-society-role",
    chapter: "energy",
    module: "society",
    when: inModule("society"),
    kind: "single",
    title: "PICK YOUR ARENA.",
    options: [
      o("court", "Arguing a case in court", "⚖️", { subjects: { law: 3 }, riasec: { E: 2 } }),
      o("policy", "Writing a new policy", "🏛️", { subjects: { "political-science": 3, economics: 1 }, riasec: { I: 1, E: 1 } }),
      o("news", "Breaking a news story", "📰", { subjects: { media: 3, "languages-literature": 1 }, riasec: { A: 1, E: 1 } }),
      o("world", "Negotiating between countries", "🌍", { subjects: { "international-relations": 3 }, riasec: { E: 2, S: 1 } }),
      o("society", "Studying how societies change", "🏙️", { subjects: { sociology: 3, history: 1 }, riasec: { I: 2, S: 1 } }),
    ],
  },
  {
    id: "dd-society-debate",
    chapter: "energy",
    module: "society",
    when: inModule("society"),
    kind: "versus",
    title: "WINNING AN ARGUMENT: LIVE DEBATE OR A KILLER ESSAY?",
    options: [
      o("debate", "Live debate", "🎙️", { subjects: { law: 2 }, riasec: { E: 2 }, learning: { discussion: 2 } }),
      o("essay", "A killer essay", "🖋️", { subjects: { history: 1, "languages-literature": 1, philosophy: 1 }, academic: { verbal: 2 } }),
    ],
  },
  {
    id: "dd-society-govt",
    chapter: "energy",
    module: "society",
    when: inModule("society"),
    kind: "slider",
    title: "HOW INTERESTED ARE YOU IN HOW GOVERNMENTS ACTUALLY WORK?",
    low: "Barely",
    high: "Very",
    lowEmoji: "🥱",
    highEmoji: "🏛️",
    fx: { subjects: { "political-science": 3, law: 1, "international-relations": 1, economics: 1 } },
  },
  {
    id: "dd-society-issue",
    chapter: "energy",
    module: "society",
    when: inModule("society"),
    kind: "multi",
    min: 1,
    title: "WHICH ISSUES WOULD YOU HAPPILY SPEND A YEAR ON?",
    sub: "Pick as many as you like.",
    options: [
      o("elections", "Elections & democracy", "🗳️", { subjects: { "political-science": 3 }, tags: { politics: 2 } }),
      o("foreign", "Wars, peace & foreign policy", "🕊️", { subjects: { "international-relations": 3 }, tags: { ir: 3 } }),
      o("rights", "Human rights & justice", "⚖️", { subjects: { law: 2, sociology: 1 }, riasec: { S: 1 } }),
      o("inequality", "Poverty & inequality", "📉", { subjects: { economics: 2, sociology: 2, "social-work": 1 } }),
      o("climate", "Climate policy", "🌍", { subjects: { environmental: 2, "political-science": 1 } }),
      o("media", "Media, truth & misinformation", "📰", { subjects: { media: 2 }, tags: { journalism: 2 } }),
      o("past", "How the past shapes today", "📜", { subjects: { history: 3 } }),
    ],
  },
  {
    id: "dd-hum-rabbit",
    chapter: "energy",
    module: "humanities",
    when: inModule("humanities"),
    kind: "multi",
    min: 1,
    title: "PICK YOUR RABBIT HOLES.",
    sub: "As many as you like.",
    options: [
      o("ruins", "Lost cities & ancient ruins", "🏺", { subjects: { history: 2 }, tags: { archaeology: 3 } }),
      o("empires", "Why empires rise and fall", "👑", { subjects: { history: 3, "political-science": 1 } }),
      o("novels", "A novel that changed the world", "📖", { subjects: { "languages-literature": 3 }, tags: { literature: 3 } }),
      o("meaning", "What makes a life meaningful", "🤔", { subjects: { philosophy: 3 } }),
      o("words", "How languages are born and change", "🗣️", { subjects: { "languages-literature": 2 }, tags: { languages: 3 } }),
      o("myths", "Myths, gods & religions", "🐉", { subjects: { history: 1, philosophy: 1, sociology: 1 }, tags: { literature: 1, archaeology: 1 } }),
      o("art", "The stories behind famous art", "🖼️", { subjects: { "visual-arts": 2, history: 1 }, tags: { museums: 2 } }),
    ],
  },
  {
    id: "dd-hum-past",
    chapter: "energy",
    module: "humanities",
    when: inModule("humanities"),
    kind: "versus",
    title: "MEETING THE PAST: DIG IT UP OR READ IT?",
    options: [
      o("dig", "Dig it up — trowel in hand", "⛏️", { subjects: { history: 2 }, tags: { archaeology: 3 }, riasec: { R: 2 }, learning: { practical: 1 } }),
      o("read", "Read it — letters, books, archives", "📜", { subjects: { history: 2, "languages-literature": 1 }, tags: { literature: 1 }, learning: { research: 2 } }),
    ],
  },
  {
    id: "dd-hum-read",
    chapter: "energy",
    module: "humanities",
    when: inModule("humanities"),
    kind: "slider",
    title: "HOW MUCH DO YOU READ JUST FOR FUN?",
    low: "Rarely",
    high: "Always",
    lowEmoji: "📵",
    highEmoji: "📚",
    fx: { subjects: { "languages-literature": 2, history: 1, philosophy: 1 }, tags: { literature: 2 }, academic: { verbal: 2 } },
  },
  {
    id: "dd-hum-project",
    chapter: "energy",
    module: "humanities",
    when: inModule("humanities"),
    kind: "single",
    title: "YOUR DREAM PROJECT?",
    options: [
      o("excavate", "Lead an excavation", "🏺", { subjects: { history: 2 }, tags: { archaeology: 3 } }),
      o("novel", "Write a novel", "✍️", { subjects: { "languages-literature": 3 }, tags: { "creative-writing": 3, literature: 1 } }),
      o("museum", "Curate a museum exhibition", "🏛️", { subjects: { history: 2, "visual-arts": 1 }, tags: { museums: 3 } }),
      o("translate", "Translate a classic into another language", "🌏", { subjects: { "languages-literature": 3 }, tags: { languages: 3 } }),
      o("argue", "Write the essay that changes a debate", "📝", { subjects: { philosophy: 2, "political-science": 1 }, tags: { politics: 1 } }),
    ],
  },
  {
    id: "dd-screen-role",
    chapter: "energy",
    module: "screen",
    when: inModule("screen"),
    kind: "single",
    title: "ON A FILM SET, YOU'RE THE…",
    options: [
      o("director", "Director", "🎬", { subjects: { media: 3 }, tags: { film: 3 }, riasec: { A: 2, E: 1 } }),
      o("writer", "Screenwriter", "📝", { subjects: { media: 2, "languages-literature": 2 }, tags: { film: 2, "creative-writing": 2 } }),
      o("camera", "Cinematographer", "🎥", { subjects: { media: 3, "visual-arts": 1 }, tags: { film: 3 }, riasec: { R: 1 } }),
      o("editor", "Editor", "✂️", { subjects: { media: 3 }, tags: { film: 2 }, academic: { technical: 1 } }),
      o("actor", "Actor", "🎭", { subjects: { "performing-arts": 3 }, tags: { theatre: 3 } }),
      o("critic", "Critic who explains why it works", "🧐", { subjects: { media: 2, "languages-literature": 1 }, tags: { film: 2, journalism: 1 }, riasec: { I: 1 } }),
    ],
  },
  {
    id: "dd-screen-make",
    chapter: "energy",
    module: "screen",
    when: inModule("screen"),
    kind: "versus",
    title: "MAKE FILMS OR STUDY THEM?",
    options: [
      o("make", "Make them", "🎞️", { subjects: { media: 2 }, tags: { film: 2 }, learning: { project: 2 } }),
      o("study", "Study them", "📚", { subjects: { media: 1, "languages-literature": 1, humanities: 1 }, tags: { film: 2 }, learning: { research: 2 } }),
    ],
  },
  {
    id: "dd-screen-analyse",
    chapter: "energy",
    module: "screen",
    when: inModule("screen"),
    kind: "slider",
    title: "AFTER A GREAT MOVIE, HOW LONG DO YOU KEEP ANALYSING IT?",
    low: "Five seconds",
    high: "Days",
    lowEmoji: "🍿",
    highEmoji: "🧠",
    fx: { subjects: { media: 2 }, tags: { film: 2 }, academic: { analytical: 1, creative: 1 } },
  },
  {
    id: "dd-screen-story",
    chapter: "energy",
    module: "screen",
    when: inModule("screen"),
    kind: "multi",
    min: 1,
    title: "YOUR KIND OF STORYTELLING?",
    sub: "Pick as many as you like.",
    options: [
      o("cinema", "Cinema", "🎬", { subjects: { media: 2 }, tags: { film: 2 } }),
      o("docs", "Documentaries", "🌍", { subjects: { media: 2 }, tags: { film: 1, journalism: 1 } }),
      o("news", "Reporting & podcasts", "🎙️", { subjects: { media: 2 }, tags: { journalism: 2 } }),
      o("stage", "Theatre", "🎭", { subjects: { "performing-arts": 2 }, tags: { theatre: 2 } }),
      o("games", "Games & animation", "🎮", { subjects: { design: 2, "computer-science": 1 } }),
      o("ads", "Ads & brand campaigns", "📣", { subjects: { media: 1, business: 1 } }),
    ],
  },
  {
    id: "dd-science-kind",
    chapter: "energy",
    module: "science",
    when: inModule("science"),
    kind: "single",
    title: "YOUR KIND OF SCIENCE?",
    options: [
      o("lab", "Experiments in a lab", "🧫", { subjects: { chemistry: 2, biology: 1, biotechnology: 1 }, riasec: { I: 2, R: 1 } }),
      o("theory", "Theory and equations", "∑", { subjects: { physics: 2, mathematics: 3 }, academic: { quantitative: 2 } }),
      o("field", "Fieldwork outdoors", "🏕️", { subjects: { environmental: 3, geography: 2, agriculture: 1 }, riasec: { R: 2 } }),
      o("data", "Finding patterns in data", "🧮", { subjects: { "data-science": 2, statistics: 2 }, riasec: { I: 2, C: 1 } }),
    ],
  },
  {
    id: "dd-science-pure",
    chapter: "energy",
    module: "science",
    when: inModule("science"),
    kind: "versus",
    title: "DISCOVER SOMETHING NEW OR INVENT SOMETHING USEFUL?",
    options: [
      o("discover", "Discover", "🔭", { subjects: { physics: 2, biology: 1, chemistry: 1 }, learning: { research: 2 } }),
      o("invent", "Invent", "💡", { subjects: { engineering: 2, biotechnology: 1 }, riasec: { R: 1, E: 1 } }),
    ],
  },
  {
    id: "dd-science-phd",
    chapter: "energy",
    module: "science",
    when: inModule("science"),
    kind: "slider",
    title: "SPEND YEARS GOING DEEP ON ONE QUESTION?",
    low: "Sounds lonely",
    high: "Sounds amazing",
    lowEmoji: "😶",
    highEmoji: "🤓",
    fx: { learning: { research: 3, independent: 1 }, motivation: { challenge: 2 }, trait: { breadth: -1 }, env: { research: 2 } },
  },

  /* ------------------------------ 03 YOUR FUTURE ----------------------------- */
  {
    id: "values",
    chapter: "future",
    kind: "rank",
    pick: 3,
    title: "WHAT MATTERS MOST IN A CAREER?",
    sub: "Rank your top three.",
    options: [
      o("money", "Earning a lot", "💰", { motivation: { income: 3 } }),
      o("impact", "Making a real difference", "🌍", { motivation: { impact: 3 }, riasec: { S: 1 } }),
      o("freedom", "Creative freedom", "🎨", { motivation: { creativity: 3 }, riasec: { A: 1 } }),
      o("security", "Stability & security", "🛡️", { motivation: { security: 3 }, trait: { risk: -1 } }),
      o("prestige", "Respect & prestige", "🏆", { motivation: { prestige: 3 } }),
      o("lead", "Leading people", "👑", { motivation: { leadership: 3 }, riasec: { E: 1 } }),
      o("hard", "Solving hard problems", "🧠", { motivation: { challenge: 3 }, riasec: { I: 1 } }),
      o("abroad", "Working around the world", "✈️", { motivation: { mobility: 3 } }),
      o("life", "A life outside work", "🌴", { motivation: { balance: 3 } }),
    ],
  },
  {
    id: "crore",
    chapter: "future",
    kind: "versus",
    title: "WHICH WOULD YOU RATHER HAVE?",
    options: [
      o("crore", "₹1 crore a year, in a stressful career", "💰", { motivation: { income: 3, prestige: 1 }, trait: { ambition: 2 } }),
      o("balance", "₹40 lakh a year, with great work-life balance", "⚖️", { motivation: { balance: 3, security: 1 } }),
    ],
  },
  {
    id: "founder",
    chapter: "future",
    kind: "versus",
    title: "FIVE YEARS AFTER GRADUATING, YOU'D RATHER BE…",
    options: [
      o("founder", "Running my own startup", "🚀", { motivation: { entrepreneurship: 3 }, trait: { risk: 2, independence: 1 }, riasec: { E: 2 } }),
      o("company", "Rising fast at a top company", "🏢", { motivation: { prestige: 2, security: 1 }, trait: { structure: 1 } }),
    ],
  },
  {
    id: "help",
    chapter: "future",
    kind: "slider",
    title: "HOW IMPORTANT IS IT THAT YOUR WORK HELPS PEOPLE DIRECTLY?",
    low: "Nice to have",
    high: "Non-negotiable",
    lowEmoji: "🤏",
    highEmoji: "❤️",
    fx: { motivation: { impact: 3 }, riasec: { S: 2 } },
  },
  {
    id: "careers",
    chapter: "future",
    kind: "multi",
    min: 1,
    title: "WHICH OF THESE COULD YOU SEE YOURSELF DOING?",
    sub: "Pick as many as you like. Gut feel is fine.",
    options: [
      o("finance", "Investing & finance", "📈", { subjects: { finance: 2, economics: 1 }, riasec: { E: 1, C: 1 } }),
      o("consult", "Consulting", "💼", { subjects: { business: 2, economics: 1 }, riasec: { E: 2 } }),
      o("software", "Software & AI", "🤖", { subjects: { "computer-science": 2, "data-science": 2 } }),
      o("engineer", "Engineering", "⚙️", { subjects: { engineering: 3 } }),
      o("doctor", "Medicine & healthcare", "🩺", { subjects: { medicine: 3, "allied-health": 1 } }),
      o("research", "Science & research", "🔬", { subjects: { physics: 1, biology: 1, chemistry: 1 }, learning: { research: 2 } }),
      o("law", "Law", "⚖️", { subjects: { law: 3 } }),
      o("policy", "Government & policy", "🏛️", { subjects: { "political-science": 2, economics: 1 } }),
      o("design", "Design & architecture", "📐", { subjects: { design: 2, architecture: 2 } }),
      o("media", "Media & entertainment", "🎬", { subjects: { media: 3 } }),
      o("film", "Making films & TV", "🎥", { subjects: { media: 3, "performing-arts": 1 }, tags: { film: 3 } }),
      o("journalist", "Journalism", "📰", { subjects: { media: 2, "languages-literature": 1 }, tags: { journalism: 3 } }),
      o("writer", "Writing & publishing", "✍️", { subjects: { "languages-literature": 3 }, tags: { literature: 2, "creative-writing": 2 } }),
      o("heritage", "Museums, heritage & archaeology", "🏺", { subjects: { history: 3 }, tags: { archaeology: 2, museums: 2 } }),
      o("diplomat", "Diplomacy & international work", "🌐", { subjects: { "international-relations": 3, "political-science": 1 }, tags: { ir: 3 } }),
      o("psych", "Psychology & counselling", "🧠", { subjects: { psychology: 3 } }),
      o("teach", "Teaching & education", "🍎", { subjects: { education: 3 } }),
      o("own", "Running a business", "🏪", { subjects: { business: 2, commerce: 1 }, motivation: { entrepreneurship: 2 } }),
      o("sport", "Sport & fitness", "🏅", { subjects: { "sports-management": 3 } }),
    ],
  },
  {
    id: "specialist",
    chapter: "future",
    kind: "versus",
    title: "GO DEEP OR GO WIDE?",
    options: [
      o("deep", "Master one thing", "🎯", { trait: { breadth: -2 }, learning: { independent: 1 } }),
      o("wide", "Be good at many things", "🌈", { trait: { breadth: 2, flexibility: 1 } }),
    ],
  },
  {
    id: "sure",
    chapter: "future",
    kind: "single",
    title: "HOW SURE ARE YOU ABOUT WHAT YOU WANT TO STUDY?",
    options: [
      o("sure", "Very sure", "📌", { trait: { flexibility: -2 } }),
      o("direction", "I have a direction", "🧭", { trait: { flexibility: 1 } }),
      o("noidea", "No idea yet — that's why I'm here", "🤷", { trait: { flexibility: 3, breadth: 1 } }),
    ],
  },

  /* ---------------------------- 04 YOUR UNIVERSITY --------------------------- */
  {
    id: "city",
    chapter: "university",
    kind: "single",
    title: "WHERE DO YOU WANT TO WAKE UP?",
    options: [
      o("bigcity", "In a buzzing big city", "🏙️", { env: { bigCity: 3, careerFocus: 1 } }),
      o("campus", "On a big leafy campus", "🌳", { env: { campusLife: 3 } }),
      o("town", "In a calm, smaller town", "🏡", { env: { smallTown: 3, bigCity: -2 } }),
      o("any", "Don't mind", "🤷", { trait: { flexibility: 1 } }),
    ],
  },
  {
    id: "size",
    chapter: "university",
    kind: "versus",
    title: "HUGE UNIVERSITY OR SMALL, CLOSE-KNIT COLLEGE?",
    options: [
      o("huge", "Huge — thousands of people, endless options", "🏟️", { env: { large: 3 }, trait: { breadth: 1 } }),
      o("small", "Small — everyone knows your name", "🏠", { env: { small: 3 } }),
    ],
  },
  {
    id: "vibe",
    chapter: "university",
    kind: "versus",
    title: "THE VIBE YOU WANT IN CLASS?",
    options: [
      o("compete", "Competitive — push me", "🔥", { env: { competitive: 3 }, trait: { competition: 2, ambition: 1 } }),
      o("collab", "Collaborative — lift each other up", "🤝", { env: { collaborative: 3 }, trait: { collaboration: 2 } }),
    ],
  },
  {
    id: "internships",
    chapter: "university",
    kind: "slider",
    title: "HOW MUCH DO INTERNSHIPS & INDUSTRY LINKS MATTER TO YOU?",
    low: "Not much",
    high: "Everything",
    lowEmoji: "🤷",
    highEmoji: "💼",
    fx: { env: { careerFocus: 3 }, learning: { practical: 1 } },
  },
  {
    id: "musthaves",
    chapter: "university",
    kind: "multi",
    min: 0,
    title: "CAMPUS MUST-HAVES?",
    sub: "Pick as many as you want — or skip.",
    options: [
      o("sport", "Great sports facilities", "🏟️", { env: { sport: 3 } }),
      o("fests", "Big fests & clubs", "🎪", { env: { culture: 3, campusLife: 1 } }),
      o("labs", "Serious research labs", "🔬", { env: { research: 3 } }),
      o("startup", "A startup incubator", "🚀", { env: { entrepreneurial: 3 } }),
      o("hostel", "Living on campus", "🛏️", { env: { campusLife: 3 } }),
      o("global", "Students from everywhere", "🌏", { env: { international: 3 } }),
    ],
  },
  {
    id: "explore",
    chapter: "university",
    kind: "versus",
    title: "PICK ONE SUBJECT FROM DAY ONE, OR EXPLORE FIRST?",
    options: [
      o("dayone", "From day one", "🎯", { trait: { breadth: -1, structure: 1 } }),
      o("explore", "Explore first, decide later", "🗺️", { trait: { flexibility: 2, breadth: 2 }, subjects: { "liberal-arts": 2 } }),
    ],
  },

  {
    id: "gendered",
    chapter: "university",
    kind: "single",
    title: "SHOULD WE INCLUDE SINGLE-GENDER COLLEGES?",
    sub: "Chennai has some excellent women's colleges. Your call.",
    options: [
      o("coed", "Co-ed only, please", "👫"),
      o("women", "Include women's colleges", "👩‍🎓"),
      o("men", "Include men's colleges", "👨‍🎓"),
    ],
  },

  /* ------------------------------- 05 YOUR WORLD ----------------------------- */
  {
    id: "home",
    chapter: "world",
    kind: "single",
    title: "WHERE ARE YOU RIGHT NOW?",
    options: [o("chennai", "Chennai", "📍"), o("tn", "Elsewhere in Tamil Nadu", "🌴"), o("india", "Elsewhere in India", "🇮🇳"), o("abroad", "Outside India", "✈️")],
  },
  {
    id: "distance",
    chapter: "world",
    kind: "single",
    title: "HOW FAR ARE YOU READY TO GO? 🌎",
    options: [
      o("city", "Stay in my city", "🏠", { trait: { risk: -1 } }),
      o("state", "Anywhere in my state", "🚗"),
      o("india", "Anywhere in India", "🚆"),
      o("india-abroad", "India or abroad — open to both", "🌏", { motivation: { mobility: 1 } }),
      o("abroad", "Abroad, ideally", "✈️", { motivation: { mobility: 2 }, trait: { risk: 1 } }),
    ],
  },
  {
    id: "regions",
    chapter: "world",
    when: abroadOpen,
    kind: "multi",
    min: 0,
    title: "WHERE ABROAD SOUNDS EXCITING?",
    sub: "Pick any — or none if you're not sure.",
    options: [
      o("usa", "USA", "🇺🇸"),
      o("uk", "UK & Ireland", "🇬🇧"),
      o("canada", "Canada", "🇨🇦"),
      o("australia", "Australia", "🇦🇺"),
      o("singapore", "Singapore", "🇸🇬"),
      o("europe", "Europe", "🇪🇺"),
      o("uae", "UAE", "🇦🇪"),
      o("hong-kong", "Hong Kong", "🇭🇰"),
      o("east-asia", "Japan & Korea", "🇯🇵"),
    ],
  },
  {
    id: "exclude",
    chapter: "world",
    when: abroadOpen,
    kind: "multi",
    min: 0,
    title: "ANY HARD NO'S?",
    sub: "Places you'd never go. Skip if none.",
    options: [
      o("usa", "USA", "🇺🇸"),
      o("uk", "UK & Ireland", "🇬🇧"),
      o("canada", "Canada", "🇨🇦"),
      o("australia", "Australia", "🇦🇺"),
      o("singapore", "Singapore", "🇸🇬"),
      o("europe", "Europe", "🇪🇺"),
      o("uae", "UAE", "🇦🇪"),
      o("hong-kong", "Hong Kong", "🇭🇰"),
      o("east-asia", "Japan & Korea", "🇯🇵"),
    ],
  },
  {
    id: "afterwards",
    chapter: "world",
    kind: "versus",
    title: "AFTER GRADUATING, WHERE DO YOU SEE YOURSELF?",
    options: [
      o("world", "Working anywhere in the world", "🌍", { motivation: { mobility: 3 }, env: { international: 2 } }),
      o("home", "Building my life closer to home", "🏡", { motivation: { security: 1, balance: 1 } }),
    ],
  },

  /* ----------------------------- 06 THE REAL WORLD ---------------------------- */
  {
    id: "budget",
    chapter: "money",
    kind: "single",
    title: "LET'S TALK MONEY. 💸",
    sub: "What yearly cost — fees plus living — would feel comfortable for your family? A rough range is perfect.",
    options: [
      o("lt1", "Under ₹1 lakh", "🪙"),
      o("1-3", "₹1–3 lakh", "💵"),
      o("3-6", "₹3–6 lakh", "💵"),
      o("6-12", "₹6–12 lakh", "💰"),
      o("12-25", "₹12–25 lakh", "💰"),
      o("25-50", "₹25–50 lakh", "💎"),
      o("50+", "₹50 lakh or more", "💎"),
      o("unsure", "Not sure yet", "🤔"),
    ],
  },
  {
    id: "scholarships",
    chapter: "money",
    kind: "slider",
    title: "HOW IMPORTANT ARE SCHOLARSHIPS FOR YOU?",
    low: "Nice bonus",
    high: "Make or break",
    lowEmoji: "🙂",
    highEmoji: "🎯",
    fx: {},
  },
  {
    id: "loan",
    chapter: "money",
    kind: "single",
    title: "HOW DO YOU FEEL ABOUT AN EDUCATION LOAN?",
    options: [
      o("none", "I'd rather avoid loans", "🙅"),
      o("small", "A small one is okay", "🤏"),
      o("worth", "A bigger one, if it's clearly worth it", "📈"),
      o("large", "Whatever it takes", "🚀", { trait: { risk: 1 } }),
    ],
  },
  {
    id: "value",
    chapter: "money",
    kind: "versus",
    title: "TWO OFFERS. WHICH ONE?",
    options: [
      o("value", "A solid college at a third of the price", "🧠", {}, "Strong outcomes, lower cost"),
      o("brand", "A famous name that stretches the budget", "✨", { motivation: { prestige: 2 } }, "Bigger brand, bigger bill"),
    ],
  },

  /* ------------------------------- 07 YOUR CALL ------------------------------ */
  {
    id: "board",
    chapter: "call",
    kind: "single",
    title: "WHICH BOARD ARE YOU IN?",
    options: [o("CBSE", "CBSE", "📘"), o("STATE_BOARD", "State board", "📗"), o("ISC", "ISC / CISCE", "📙"), o("IB", "IB", "🌐"), o("A_LEVELS", "A-levels", "🇬🇧"), o("OTHER", "Something else", "📓")],
  },
  {
    id: "ibsubjects",
    chapter: "call",
    when: ({ answers }) => answers.board === "IB",
    kind: "subjects",
    scheme: "IB",
    title: "YOUR IB SUBJECTS & PREDICTED GRADES",
    sub: "Pick your six subjects, set HL or SL, and your predicted grade. Rough is fine.",
  },
  {
    id: "alsubjects",
    chapter: "call",
    when: ({ answers }) => answers.board === "A_LEVELS",
    kind: "subjects",
    scheme: "A_LEVELS",
    title: "YOUR A-LEVELS & PREDICTED GRADES",
    sub: "Pick your subjects and predicted grades.",
  },
  {
    id: "stream",
    chapter: "call",
    when: ({ answers }) => !["IB", "A_LEVELS"].includes(String(answers.board ?? "")),
    kind: "single",
    title: "YOUR CLASS 11–12 SUBJECTS?",
    options: [
      o("pcm", "Physics, Chemistry, Maths", "📐"),
      o("pcb", "Physics, Chemistry, Biology", "🧬"),
      o("pcmb", "PCM + Biology", "🔬"),
      o("commerce-maths", "Commerce with Maths", "📊"),
      o("commerce", "Commerce without Maths", "🧾"),
      o("humanities", "Humanities / Arts", "📚"),
      o("undecided", "Haven't chosen yet", "🤔"),
    ],
  },
  {
    id: "marks",
    chapter: "call",
    when: ({ answers }) => !["IB", "A_LEVELS"].includes(String(answers.board ?? "")),
    kind: "single",
    title: "MARKS YOU EXPECT (OR GOT) IN CLASS 12?",
    sub: "A range is enough. This only helps us be realistic.",
    options: [o("95", "95% or above", "🏆"), o("90", "90–95%", "⭐"), o("80", "80–90%", "👍"), o("70", "70–80%", "🙂"), o("60", "60–70%", "🤞"), o("50", "Below 60%", "🌱"), o("unknown", "Not sure yet", "🤔")],
  },
  {
    id: "exams",
    chapter: "call",
    kind: "multi",
    min: 0,
    title: "ANY ENTRANCE EXAMS ON YOUR LIST?",
    sub: "Pick any you've taken or plan to. Skip if none.",
    options: [o("JEE", "JEE", "⚙️"), o("NEET", "NEET", "🩺"), o("CUET", "CUET", "📝"), o("CLAT", "CLAT", "⚖️"), o("IPMAT", "IPMAT", "📈"), o("SAT", "SAT / ACT", "🇺🇸"), o("NATA", "NATA", "📐"), o("IELTS", "IELTS / TOEFL", "🗣️")],
  },
  {
    id: "risk",
    chapter: "call",
    kind: "versus",
    title: "YOUR APPLICATION STRATEGY?",
    options: [
      o("bold", "Shoot for the stars", "🌠", { trait: { risk: 3, ambition: 2 } }),
      o("safe", "Lock in a sure thing first", "🔒", { trait: { risk: -2, structure: 1 }, motivation: { security: 1 } }),
    ],
  },
];

export const QUESTION_BY_ID = Object.fromEntries(QUESTIONS.map((q) => [q.id, q])) as Record<string, Question>;
